### ISSUE TITLE
Box plot wrongly claculating whiskers

### ISSUE THREAD

**Issue by fisadev** [Kozea/pygal#149]
The current implementation doesn't matches any of the known ways of choosing the whiskers extremes. In every known method, the extremes **can't be outside** the range of the data, and pygal draws whiskers outside the range of the data (example: the box plot in the docs). Pygal uses the 1.5*IQR to calculate the whiskers, but the correct way to use the 1.5*IQR is well explained in wikipedia:
 
    the lowest datum still within 1.5 IQR of the lower quartile, and the highest datum still within 1.5 IQR of the upper quartile (often called the Tukey boxplot)

Note this: it's using the lowest and highest **datum** inside the 1.5*IQR range, and **not** the 1.5*IQR values.

http://en.wikipedia.org/wiki/Box_plot

**Comment by dzejar** [comment]
I encountered the same problem. After deciding to fix it myself I've found that since [this commit] (https://github.com/Kozea/pygal/commit/0e2272e0a495b7029afdf835b944c0a13f7fc1ac) it is fixed if you use `mode="extremes"` argument.

Note: It is still not the right box plot as the whiskers contain all the outliers also, but it's much better than the original mode.

Fixed box plot example from [pygal.org examples](http://pygal.org/chart_types/#idid6):
```python
box_plot = pygal.Box(mode="extremes")
box_plot.title = 'V8 benchmark results'
box_plot.add('Chrome', [6395, 8212, 7520, 7218, 12464, 1660, 2123, 8607])
box_plot.add('Firefox', [7473, 8099, 11700, 2651, 6361, 1044, 3797, 9450])
box_plot.add('Opera', [3472, 2933, 4203, 5229, 5810, 1828, 9013, 4669])
box_plot.add('IE', [43, 41, 59, 79, 144, 136, 34, 102])
box_plot.render()
```

**Comment by jonathanstiansen** [comment]
@dzejar Yes I'm finding that works as well, though it's not intuitive - it's a hack. At the very least that should be the default mode, no?
