### ISSUE TITLE
render_to_png utf-8 not disable?

### ISSUE THREAD

**Issue by freetest** [Kozea/pygal#320]
render_to_png utf-8 not disable?

![ee](https://cloud.githubusercontent.com/assets/5380255/15388545/f86de4d4-1de4-11e6-8671-773db628be30.png)

**Comment by freetest** [comment]
@liZe   what font_family i set  will  show  utf-8 ?   need i put the  .ttf  in where?

**Comment by liZe** [comment]
You need to set a font-family that has the glyphs you want (for example, a font with Chinese characters if you need them). The font needs to be installed on your system.

**Comment by freetest** [comment]
@liZe  thanks i use "Lantinghei SC" fix it~

**Comment by huyujie** [comment]
@freetest can you tell me how to add Chinese *.ttf font-family, give me some CodeSnippet?

**Comment by huyujie** [comment]
@liZe @freetest I installed a chainese font on system and fix it by add  style=BlueStyle(legend_font_family='SIMHEI',title_font_family='SIMHEI')

**Comment by dwasss** [comment]
I had the same issue as in https://github.com/Kozea/pygal/issues/384 "changing googlefonts makes no difference" where it displayed boxes like [] instead of rendering the Japanese characters from Noto Sans JP googlefont. This happened when cairosvg rendered the graph in PNG or when the SVG-version of the graph (which worked fine) was embedded in the HTML and then converted to PDF via cairosvg/weasyprint.

The workaround was to follow the advice in this issue and install the googlefont on the system (or Docker instance, in my case) using guidance in https://gist.github.com/lightonphiri/5811226a1fba0b3df3be73ff2d5b351c. The easiest thing was to add `RUN apt install -y fonts-noto-cjk` in my Dockerfile and put `custom_style = Style(font_family='Noto Sans CJK JP')` in my python script.
